### PR TITLE
Delete index.bak.js

### PR DESCRIPTION
**Pull request by albertz**
I guess this was a backup file, which is not really needed, as you have it in the Git history.

### CODE REVIEW

**Comment by alerque** [comment]
Probably should add a .gitignore that covers this so it doesn't happen again too ;-)

**Comment by mrunge** [comment]
> Probably should add a .gitignore that covers this so it doesn't happen again too ;-)

I disagree with that comment, for better `.gitignore` handling, see https://julien.danjou.info/properly-managing-your-gitignore/

**Comment by alerque** [comment]
Just a very small "heads up" tip about Open Source projects @elliott-wen ... if you want to foster a project that people are interested in contributing back to long term, a little bit goes a long way. When people send PR's, go a little out of your way to adapt the PR even if it means cherry picking commits, or pushing a tweak to the PR branch before squashing or whatever. In this case going off and deleting the file in your own commit is a minor thing and I'm sure not a big deal to anybody, but since this project is just getting rolling and attracting a lot of attention I thought I'd mention as somebody who has worked on a lot of OSS (from all ends: using, contributing, and managing) that little things like going off and deleting a file yourself instead of accepting the PR from somebody that went to the effort of doing it for you can be little turn offs. On the other hand accepting even little minor things can often rope people in and encourage bigger contributions down the road as they know you'll work with them to make it happen.

**Comment by alerque** [comment]
@mrunge Fair enough. I assumed it was an artifact of the build system, if it was an artifact of a user's local workflow that's a little different.

**Comment by elliott-wen** [comment]
Thanks Caleb.

That's a really good suggestion.

Cheers
Elliott

**Comment by mrunge** [comment]
@alerque Caleb, I'm sorry, I did not want to sound arrogant. You were suggesting a solution, which would have prevented such a file to land in a repository. 

@elliott-wen Closing this and doing the same on your own as in https://github.com/SwiftLaTeX/SwiftLaTeX/commit/5302991241feb3bcb0f4afb1ce9b5f75721f40cb is quite discouraging for external contributors. I can only second @alerque s comment https://github.com/SwiftLaTeX/SwiftLaTeX/pull/11#issuecomment-562438401.

**Comment by elliott-wen** [comment]
Will pay attention to this matter next time. Really sorry for
any inconvenience caused.

Cheers
Elliott

**Pull request closed without merging**
